### ISSUE TITLE
Relationship to GraphQL?

### ISSUE THREAD

**Issue by developit** [bicyclejs/bicycle#1]
This project looks really interesting. Quick question - is the intention to support a "graphql-like" query syntax, or full GraphQL?

**Comment by ForbesLindesay** [comment]
The intention is to support something very similar to graph-ql syntax.  For example we have https://github.com/bicyclejs/babel-plugin-transform-bql which lets you use a very similar syntax to declare your queries.

I don't currently have plans to support using graphql as the actual protocol between client and server because bicycle requires the server to do diffing of both query and response.  This is not something that any graphql servers do.

**Comment by developit** [comment]
Great explanation, thanks for the detail.
