### ISSUE TITLE
How to handle pagination and related objects?

### ISSUE THREAD

**Issue by jaredpalmer** [bicyclejs/bicycle#2]
This is really cool btw 👍

**Comment by ForbesLindesay** [comment]
You can handle related objects by making related objects be fields of each other.  In the example (https://github.com/bicyclejs/bicycle/blob/master/example/schema/objects/root.js) the `Root` object is related to the `Todo` object in that it has a list of all the todos in the `todos` field.  Because fields are only read if the client requests them, it is ok to have cycles in your schema.

Pagination is currently a little awkward.  It's something I would like to make easier in the future.  You can currently hack around it by having a field in your schema that looks like:

```js
    todos: {
      type: 'Todo[]',
      args: {limit: 'number'},
      resolve(root, {limit}, {user}) {
        return getTodos();
      },
    },
```

then on the client you can have something like this (assuming you are using [`bql`](https://github.com/bicyclejs/babel-plugin-transform-bql) for your bicycle queries and react for your application):

```js
function paginator(Component) {
  class Paginator extends React.Component {
    constructor() {
      super();
      this.state = {pages: 1};
      this._onNextPage = this._onNextPage.bind(this);
    }
    _onNextPage() {
      this.setState(s => {pages: s.pages + 1});
    }
    render() {
      return <Component {...this.props} pages={this.state.pages} onNextPage={this._onNextPage} />
    }
  }
  return Paginator;
}

function List({todos, onNextPage}) {
  return (
    <div>
      <ul>
        {todos.map(t => <li>{t.name}</li>)}
      </ul>
      <button onClick={onNextPage}>Next Page</button>
    </div>
  );
}
const ITEMS_PER_PAGE = 10;
const ListContainer = paginator(connect(
  props => bql`
    todos(limit: ${props.pages * ITEMS_PER_PAGE}) {
      name
    }
  `,
)(List));
```

The paginator is a higher order component, that lets us extract the state of "which page are we on" and the `limit` parameter allows us to tell bicycle how many items we want.  Because bicycle diffs the data before sending it back to the client, we won't be wasting much time on loading the records that we already have.

Ideally, I would like to add a feature to bicycle so you would be able to do something like:

```js
function List({todos}) {
  return (
    <div>
      <ul>
        {todos.map(t => <li>{t.name}</li>)}
      </ul>
      <button onClick={todos.getNextPage}>Next Page</button>
    </div>
  );
}
const ITEMS_PER_PAGE = 10;
const ListContainer =connect(
  props => bql`
    todos$paginated(perPage: ${ITEMS_PER_PAGE}) {
      name
    }
  `,
)(List);
```

This would require:

1. Updating the server side of bicycle to support a special kind of `$limit` argument to `Array` fields that would limit the number of items returned.  This way the schema would not have to be modified to support pagination.
2. Updating the client so that it accepts a special `$paginated` tag as part of the query, and if so, passes on the appropriate `$limit` to the server and includes a `getNextPage` function in the result.
3. Updating bql to support an appropriate short-hand for marking a query as paginated.

It would also be worthwhile to update the diff-cache and merge-cache [utils](https://github.com/bicyclejs/bicycle/tree/master/src/utils) to actually diff and merge arrays properly, since we would currently be sending all the IDs even though most responses just append to the array.

**Comment by jaredpalmer** [comment]
Interesting. Reminds me of a HOC I wrote to handle pagination with ParseReact's `observe()` back when that was still a thing. 

I like the idea of a `$limit` and `$paginated`. That would be perfect.
